export const REQUEST_PROTOCOL = 'ULTIMATEBRIDGE_REQUEST_V1';
export const REPORT_PROTOCOL = 'ULTIMATEBRIDGE_RUNNER_REPORT_V1';
export const ATTACHMENT_PROTOCOL = 'ULTIMATEBRIDGE_ATTACHMENT_MANIFEST_V1';

export const MODES = Object.freeze([
  'READ_ONLY',
  'SAFE_CHANGE_PREVIEW',
  'SAFE_CHANGE',
  'PROJECT_CHANGE',
  'EXECUTION_LOCKED'
]);

export const REPORT_STATUSES = Object.freeze([
  'OK',
  'WARN',
  'ERROR',
  'BLOCKED',
  'TIMEOUT'
]);

export const DEFAULT_DIRECT_REPORT_LIMIT = 12000;
